services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - backend

  fastapi:
    build:
      context: ./fastapi
      dockerfile: dockerfiles/fastapi.dockerfile
    ports:
      - "7000:7000"
    networks:
      - app_network
    depends_on:
      - backend
      - selenium_scraper
  
  celery_worker:
    build:
      context: ./fastapi
      dockerfile: dockerfiles/celery.dockerfile
    container_name: celery_worker
    volumes:
      - ./fastapi/celery_app:/celery_app
    networks:
      - app_network
    depends_on:
      - redis
      - selenium_scraper

  celery_beat:
    build:
      context: ./fastapi
      dockerfile: dockerfiles/celery.dockerfile
    container_name: celery_beat
    command: celery -A celery_app beat --loglevel=info
    networks:
      - app_network
    depends_on:
      - redis
      - backend
      - selenium_scraper

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - app_network
    

  backend:
    build:
      context: ./backend
      dockerfile: dockerfiles/python.dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app_network
    depends_on:
      - postgresdb
  
  postgresdb:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  selenium_scraper:
    image: selenium/standalone-chrome
    ports: 
      - "4444:4444"
    networks:
      - app_network

  flask_blog:
    build:
      context: ./flask_blog
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - postgresdb
      - backend

networks:
  app_network:

volumes:
  postgres_data: